training_pipeline_config:
  pipeline_name: CreditCard
  artifact_dir: artifact

data_ingestion_config:
  dataset_download_id: https://raw.githubusercontent.com/pk1308/datasets/master/ucicredit/UCI_Credit_Card.csv
  dataset_download_file_name : UCI_Credit_Card.csv
  ingestion_dir : Stage00_data_ingestion
  raw_data_dir: raw_data
  ingested_dir: ingested_data
  ingested_train_file: train.csv
  ingested_test_file: test.csv